name: Auto-Approve and Auto-Merge Dependabot Minor Updates

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main] # Target branch(es) for the auto-merge

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    # if: ${{ github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'Bump') && !contains(github.event.pull_request.title, 'major') }}
    if: github.event.label.name == 'hello'
    steps:
      - name: Auto-approve Dependabot PR
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    needs: auto-approve
    runs-on: ubuntu-latest
    # if: ${{ github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'Bump') && !contains(github.event.pull_request.title, 'major') }}
    if: github.event.label.name == 'hello'
    steps:
      - name: Auto-merge Dependabot PR
        uses: peter-evans/merge-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash # Options: merge, squash, rebase